services:
  react-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
